import { ROLES, RoleType } from './roles';

export const PERMISSIONS = {
  // Organisation Management
  ORG_READ: 'organisation:read',
  ORG_UPDATE: 'organisation:update',
  ORG_DELETE: 'organisation:delete',
  ORG_ACCESS_MANAGE: 'organisation:access_manage',

  // Team & Member Management
  TEAM_READ: 'team:read',
  TEAM_INVITE: 'team:invite',
  TEAM_MANAGE: 'team:manage',

  // Event & Album Management
  EVENT_READ: 'event:read',
  EVENT_CREATE: 'event:create',
  EVENT_UPDATE: 'event:update',
  EVENT_DELETE: 'event:delete',

  // Media Operations
  MEDIA_UPLOAD_OFFICIAL: 'media:upload_official',
  MEDIA_UPLOAD_COMMUNITY: 'media:upload_community',
  MEDIA_PUBLISH: 'media:publish',
  MEDIA_DELETE: 'media:delete',
  MEDIA_MODERATE: 'media:moderate',

  // Observability & Compliance
  AUDIT_READ: 'audit:read',
  ANALYTICS_READ: 'analytics:read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Role-to-Permissions Matrix
 */
export const ROLE_PERMISSIONS: Record<RoleType, readonly Permission[]> = {
  [ROLES.PLATFORM_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ORGANISATION_OWNER]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.ORG_DELETE,
    PERMISSIONS.ORG_ACCESS_MANAGE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_INVITE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.MEDIA_UPLOAD_OFFICIAL,
    PERMISSIONS.MEDIA_UPLOAD_COMMUNITY,
    PERMISSIONS.MEDIA_PUBLISH,
    PERMISSIONS.MEDIA_DELETE,
    PERMISSIONS.MEDIA_MODERATE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],

  [ROLES.ORGANISATION_ADMIN]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.ORG_ACCESS_MANAGE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_INVITE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.MEDIA_UPLOAD_OFFICIAL,
    PERMISSIONS.MEDIA_UPLOAD_COMMUNITY,
    PERMISSIONS.MEDIA_PUBLISH,
    PERMISSIONS.MEDIA_DELETE,
    PERMISSIONS.MEDIA_MODERATE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],

  [ROLES.SOCIAL_MEDIA_MANAGER]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.MEDIA_UPLOAD_OFFICIAL,
    PERMISSIONS.MEDIA_UPLOAD_COMMUNITY,
    PERMISSIONS.MEDIA_PUBLISH,
    PERMISSIONS.MEDIA_DELETE,
    PERMISSIONS.MEDIA_MODERATE,
    PERMISSIONS.ANALYTICS_READ,
  ],

  [ROLES.MODERATOR]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.MEDIA_UPLOAD_COMMUNITY,
    PERMISSIONS.MEDIA_MODERATE,
  ],

  [ROLES.SOCIAL_MEDIA_MEMBER]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.MEDIA_UPLOAD_OFFICIAL,
    PERMISSIONS.MEDIA_UPLOAD_COMMUNITY,
    PERMISSIONS.MEDIA_PUBLISH,
  ],

  [ROLES.USER]: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.MEDIA_UPLOAD_COMMUNITY,
  ],
};

/**
 * Checks if a given role grants a specific permission.
 */
export function checkRolePermission(role: RoleType, permission: Permission): boolean {
  const granted = ROLE_PERMISSIONS[role] || [];
  return granted.includes(permission);
}
